package agentkit

// ProcessID identifies a Process. It is a uuid v7 (time-ordered) generated by
// the Kernel via uuid.NewV7().
type ProcessID string

// AgentName is the registry key of an agent definition (name + version +
// strategy). Process.Agent stores this wire value; a typo is detected at Spawn
// time as ErrUnknownAgent.
type AgentName string

// AwaitKey is a Process-local unique key for a "wait". Strategies name it.
type AwaitKey string

// ModelRole denotes the intended use of a model (e.g. "planner"). It is a
// sealed interface: the unexported marker method modelRole() makes it
// unimplementable outside this package, so only values returned by
// DefineModelRole can exist. Resolution is by pointer identity — two Define
// calls with the same name are NOT equal. A nil ModelRole means "the default
// model" (the required argument of New). name is for diagnostics only.
type ModelRole interface {
	// String returns the diagnostic display name.
	String() string
	modelRole()
}

// modelRole is the sole implementation of ModelRole. Identity (pointer
// equality) is the comparison used to resolve a role to a client, so each
// DefineModelRole call yields a distinct role even for the same name.
type modelRole struct {
	name string
}

func (r *modelRole) String() string { return r.name }
func (r *modelRole) modelRole()     {}

// DefineModelRole returns a fresh ModelRole. Callers keep the result in a
// package variable and share that value; every call returns a new identity.
func DefineModelRole(name string) ModelRole {
	return &modelRole{name: name}
}
